apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-function
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: python-function
spec:
  source:
    git:
      url: https://github.com/seagomezar/python-function.git
      ref:
        branch: main
  build:
    env:
      - name: BP_FUNCTION
        value: func.main
